# Generated by Django 5.1.4 on 2024-12-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscrapeevent',
            name='asin',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
